# Generated by Django 3.1.6 on 2021-02-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_auto_20210223_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='steamship',
            field=models.CharField(choices=[('CMA', 'CMA'), ('HMM', 'Hyundai'), ('MSC', 'MSC'), ('OOCL', 'OOCL'), ('ONE', 'ONE'), ('ZIM', 'ZIM')], max_length=20),
        ),
    ]
