# Generated by Django 3.1.6 on 2021-02-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210223_1630'),
        ('containers', '0005_auto_20210223_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Steamship',
        ),
    ]
