# Generated by Django 3.1.6 on 2021-02-24 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0007_auto_20210223_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Please enter the container    number with no spaces and a - before the check number (eg.        ABCD123456-7).', regex='[a-zA-Z]{4}\\d{6}\\-\\d{1}')]),
        ),
    ]
