# Generated by Django 3.1.6 on 2021-02-24 03:01

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20210223_1635'),
        ('containers', '0009_auto_20210223_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='booking',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='steamship', chained_model_field='steamship', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
