# Generated by Django 3.1.6 on 2021-02-23 19:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steamship',
            fields=[
                ('abbreviation', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('street2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('railyard', models.CharField(choices=[('NS', 'NorfolkSouthern'), ('CSX', 'CSX')], max_length=20)),
                ('num_of_containers', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('container_size', models.CharField(choices=[('20', '20 foot'), ('40S', '40 foot standard'), ('40H', '40 foot highcube')], max_length=20)),
                ('sales_contract', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=50)),
                ('port_of_loading', models.CharField(max_length=50)),
                ('railcut', models.DateField()),
                ('packaging', models.CharField(max_length=20, null=True)),
                ('lot', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PS', 'Pre-Shipment'), ('LG', 'Loading'), ('LD', 'Loaded'), ('DP', 'Departed'), ('SL', 'Sailed')], default='Pre-Shipment', max_length=10)),
                ('steamship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.steamship')),
            ],
        ),
    ]
