# Generated by Django 3.1.6 on 2021-02-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sales_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.sales'),
        ),
    ]
