# Generated by Django 3.1.6 on 2021-02-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210223_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='packaging',
        ),
        migrations.AddField(
            model_name='booking',
            name='pkg',
            field=models.CharField(choices=[('BULK', 'BULK'), ('30KG', '30KG'), ('60#', '60#')], default='BULK', max_length=20),
        ),
    ]
